# For creating a new bot use https://t.me/BotFather
telegram-bot-api-key: bot_token_here
telegram-bot-username: bot_username_here
# For your telegram id use https://t.me/getmyid_bot
telegram-bot-admin-id: admin_id_here
