# For creating a new bot use https://t.me/BotFather
telegram-bot-api-key: bot_token_here
telegram-bot-username: bot_username_here
# For your telegram id use https://t.me/getmyid_bot
telegram-bot-admin-id: admin_id_here
# Some commands permissions
player-kill: true
# True if you want to limit how far players teleport using the 'rtp' command
world-border: true
border: 2000
# World name used to get world data
lobby-world: 'world'
# enable motd message
motd: true
# add and remove lines as needed for motd message
motd-message:
  - '&d&o-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-'
  - ''
  - '&aWelcome to the &c&lServer'
  - ''
  - '&d&o-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-'
# db-related constants for connection
mongodb-connection-string: connection_string_here
mongodb-database-name: quartermaster
mongodb-collection-name: locks
# enable staffhome teleportation
staffhome-enable: true
# this section holds all the locations of Temporary Homes
savedlocations:
