# For creating a new bot use https://t.me/BotFather
telegram-bot-api-key: 6031022457:AAHWip-kLQBuetURtKBdXWvWvzjSiupwAKI
telegram-bot-username: spwhelper_bot
# For your telegram id use https://t.me/getmyid_bot
telegram-bot-admin-id: 1148695153
# Some commands permissions
player-kill: true
# True if you want to limit how far players teleport using the 'rtp' command
world-border: true
border: 2000
# World name used to get world data
lobby-world: 'world'
# Enable motd message
motd: true
# Add and remove lines as needed for motd message
motd-message:
  - '&d&o-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-'
  - ''
  - '&aWelcome to the &c&lServer'
  - ''
  - '&d&o-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-'
# db-related constants for connection
mongodb-connection-string: mongodb+srv://zea1ot19:19Mongodb!19kz@papercluster.c9roepk.mongodb.net/?retryWrites=true&w=majority
mongodb-database-name: quartermaster
mongodb-collection-name: locks
# Enable staffhome teleportation
staffhome-enable: true
# Provide a material name for the blocks to be lockable: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
lockable-blocks:
  - 'CHEST'
# This section holds all the locations of Temporary Homes
savedlocations:
