name: McTelegramChat
version: '${project.version}'
main: org.amirov.mctelegramchat.McTelegramChat
api-version: 1.19
authors: [ Daniyar ]
description: This bot will help you while playing a single-player world in Minecraft
website: https://github.com/mirroxEkb14
commands:
  gui:
    description: Open GUI
    usage: /<command>
  god:
    description: Become invincible
    usage: /<command>
    permission: commands.god
    permission-message: No permission
  feed:
    description: Feed yourself
    usage: /<command>
  kill:
    description: Kill a certain player
    usage: /<command>
  setspawn:
    description: Save your spawn point
    usage: /<command>
  spawn:
    description: Teleport yourself to your spawn point
    usage: /<command>
  menu:
    description: Open an inventory
    usage: /<command>
    aliases:
      - inventory
      - gear
  fly:
    description: Fly
    usage: /<command>
  givebow:
    description: Give a teleport bow
    usage: /<command>
  armorstand:
    description: Create armorstand
    usage: /<command>
  hologram:
    description: Create a hologram
    usage: /<command>
  saveloc:
    description: Saves current location point
    usage: /<command>
permissions:
  commands.god:
    description: Allows god command
    default: false