name: McTelegramChat
version: '${project.version}'
main: org.amirov.mctelegramchat.McTelegramChat
api-version: 1.19
authors: [ Daniyar ]
description: This bot will help you while playing a single-player world in Minecraft
website: https://github.com/mirroxEkb14
commands:
  menu:
    description: Open menu
    usage: /<command>
    aliases:
      - m
  setspawn:
    description: Save your spawn point
    usage: /<command>
  spawn:
    description: Teleport yourself to your spawn point
    usage: /<command>
  saveloc:
    description: Save current location point
    usage: /<command>
  spawnsign:
    description: Spawn a sign with a text
    usage: /<command>
  ban:
    description: Open ban list
    usage: /<command>
  rtp:
    description: Random tp
    usage: /<command>
  vanish:
    description: Become visible/invisible
    usage: /<command>
  staffhome:
    description: Staffhome setting
    usage: /<command>
  scoreboard:
    description: Opens a score board
    usage: /<command>
    aliases:
      - sb
  lock:
    description: Locks a chest a player looking at
    usage: /<command>
  locklist:
    description: Opens gui with player's locks
    usage: /<command>
  prank:
    description: Contains subcommands with different ways to prank a player
    usage: /<command>
  quartermaster:
    description: Manage And Use QuarterMaster Plugin
    aliases: [qm]