name: McTelegramChat
version: '${project.version}'
main: org.amirov.mctelegramchat.McTelegramChat
api-version: 1.19
authors: [ Daniyar ]
description: This bot will help you while playing a single-player world in Minecraft
website: https://github.com/mirroxEkb14
commands:
  menu:
    description: Open menu
    usage: /<command>
    aliases:
      - m
  kill:
    description: Kill a certain player
    usage: /<command>
    aliases:
      - k
  setspawn:
    description: Save your spawn point
    usage: /<command>
  spawn:
    description: Teleport yourself to your spawn point
    usage: /<command>
    aliases:
      - s
  saveloc:
    description: Save current location point
    usage: /<command>
    aliases:
      - sl
  spawnsign:
    description: Spawn a sign with a text
    usage: /<command>
    aliases:
      - ss
  ban:
    description: Open ban list
    usage: /<command>
    aliases:
      - b