name: McTelegramChat
version: '${project.version}'
main: org.amirov.mctelegramchat.McTelegramChat
api-version: 1.19
authors: [ Daniyar ]
description: This bot will help you while playing a single-player world in Minecraft
website: https://github.com/mirroxEkb14
commands:
  die:
    description: Kill yourself instantly
    usage: /<command>
    aliases:
      - perish
      - passaway
  god:
    description: Become invincible
    usage: /<command>
    permission: commands.god
    permission-message: No permission
  feed:
    description: Feed yourself
    usage: /<command>
  kill:
    description: Kill a certain player
    usage: /<command>
  setspawn:
    description: Save your spawn point
    usage: /<command>
  spawn:
    description: Teleports you to your spawn point
    usage: /<command>
permissions:
  commands.god:
    description: Allows god command
    default: false